In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [5]:
filt = (df['last'] == 'Schafer') | (df['first'] == 'John')

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [9]:
filt = (df['last'] == 'Doe')

In [10]:
df[filt]

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [11]:
df.loc[filt]

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [6]:
df.loc[~filt, 'email']

1    JaneDoe@email.com
Name: email, dtype: str