In [1]:
people = {
    'first': ['Corey', 'Jane', 'John'], 
    'last': ['Schafer', 'Doe', 'Doe'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [5]:
df['first'] + ' ' + df['last']

0    Corey Schafer
1         Jane Doe
2         John Doe
dtype: str

In [6]:
df['full_name'] = df['first'] + ' ' + df['last']
df

   first     last                    email      full_name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

In [7]:
df.drop(columns=['first', 'last'], inplace=True)
df

                     email      full_name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [8]:
df['full_name'].str.split(' ', expand=True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [9]:
df[['first', 'last']] = df['full_name'].str.split(' ', expand=True)
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe

In [14]:
new_row = pd.DataFrame([{'first': 'Tony'}])
df = pd.concat([df, new_row], ignore_index=True)

In [15]:
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN

In [16]:
people = {
    'first': ['Tony', 'Steve'], 
    'last': ['Stark', 'Rogers'], 
    'email': ['IronMan@avenge.com', 'Cap@avenge.com']
}
df2 = pd.DataFrame(people)
df2

   first    last               email
0   Tony   Stark  IronMan@avenge.com
1  Steve  Rogers      Cap@avenge.com

In [17]:
df = pd.concat([df, df2], ignore_index=True, sort=False)

In [18]:
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN
4       IronMan@avenge.com            NaN   Tony    Stark
5           Cap@avenge.com            NaN  Steve   Rogers

In [26]:
df.drop(index=3)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
4       IronMan@avenge.com            NaN   Tony    Stark
5           Cap@avenge.com            NaN  Steve   Rogers

In [31]:
filt = df['last'] == 'Doe'
df.drop(index=df[filt].index)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
3                      NaN            NaN   Tony      NaN
4       IronMan@avenge.com            NaN   Tony    Stark
5           Cap@avenge.com            NaN  Steve   Rogers